# Generated by Django 6.0.6 on 2026-07-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['capacity', 'table_number']},
        ),
    ]
